# Generated by Django 2.2.28 on 2023-09-08 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('type', models.IntegerField()),
                ('reason', models.TextField()),
                ('paymentPeriodicity', models.IntegerField()),
                ('paymentAmount', models.FloatField()),
                ('paymentStartDate', models.DateField()),
                ('notes', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LoanAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.TextField(max_length=50)),
                ('status', models.IntegerField()),
                ('name', models.TextField()),
                ('originalBalance', models.FloatField()),
                ('saveNowPercentage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionDate', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ImportedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('filename', models.TextField()),
                ('uploadedDate', models.DateTimeField()),
                ('uploadType', models.IntegerField()),
                ('noOfRecords', models.IntegerField()),
                ('noOfRecordsProcessed', models.IntegerField()),
                ('uploadedBy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='importedfile_uploadedBy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
