# Generated by Django 2.2.28 on 2023-09-11 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_businessrule_campaign_content_merchantaccount_reporting_reward_template_useractivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipCode', models.TextField()),
                ('address1', models.TextField()),
                ('address2', models.TextField()),
                ('city', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address_city', to='home.City')),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address_country', to='home.Country')),
                ('state', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address_state', to='home.State')),
            ],
        ),
        migrations.RemoveField(
            model_name='billingdetails',
            name='billAddr',
        ),
        migrations.RemoveField(
            model_name='billingdetails',
            name='billAddrCity',
        ),
        migrations.RemoveField(
            model_name='billingdetails',
            name='billAddrCountry',
        ),
        migrations.RemoveField(
            model_name='billingdetails',
            name='billAddrState',
        ),
        migrations.RemoveField(
            model_name='billingdetails',
            name='billAddrZipCode',
        ),
        migrations.RemoveField(
            model_name='billingdetails',
            name='state',
        ),
        migrations.RemoveField(
            model_name='billingdetails',
            name='zip',
        ),
        migrations.RemoveField(
            model_name='businessownerdata',
            name='city',
        ),
        migrations.RemoveField(
            model_name='businessownerdata',
            name='country',
        ),
        migrations.RemoveField(
            model_name='businessownerdata',
            name='state',
        ),
        migrations.RemoveField(
            model_name='businessownerdata',
            name='zipCode',
        ),
        migrations.RemoveField(
            model_name='creditorbusinessdata',
            name='address1',
        ),
        migrations.RemoveField(
            model_name='creditorbusinessdata',
            name='address2',
        ),
        migrations.RemoveField(
            model_name='creditorbusinessdata',
            name='country',
        ),
        migrations.RemoveField(
            model_name='creditorbusinessdata',
            name='state',
        ),
        migrations.RemoveField(
            model_name='creditorbusinessdata',
            name='zipCode',
        ),
        migrations.AlterField(
            model_name='businessownerdata',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='businessownerdata_address', to='home.Address'),
        ),
        migrations.AddField(
            model_name='billingdetails',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billingdetails_address', to='home.Address'),
        ),
        migrations.AddField(
            model_name='billingdetails',
            name='billAddress',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billingdetails_billAddress', to='home.Address'),
        ),
        migrations.AddField(
            model_name='creditorbusinessdata',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creditorbusinessdata_address', to='home.Address'),
        ),
    ]
