# Generated by Django 2.2.28 on 2023-09-08 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20230908_2019'),
        ('users', '0003_auto_20230908_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accounts',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_accounts', to='home.LoanAccount'),
        ),
        migrations.AddField(
            model_name='user',
            name='billingDetails',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_billingDetails', to='home.BillingDetails'),
        ),
        migrations.AddField(
            model_name='user',
            name='businessData',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_businessData', to='home.CreditorBusinessData'),
        ),
        migrations.AddField(
            model_name='user',
            name='offers',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_offers', to='home.ConsumerOffer'),
        ),
        migrations.AddField(
            model_name='user',
            name='payments',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_payments', to='home.Payment'),
        ),
        migrations.AddField(
            model_name='user',
            name='subscription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_subscription', to='home.Subscription'),
        ),
    ]
