from django.contrib import admin
from .models import Address,BillingDetails,BusinessOwnerData,BusinessRule,Campaign,City,ConsumerOffer,Content,Country,CreditorBusinessData,Donation,ImportedFile,LoanAccount,MembershipPlan,MerchantAccount,Payment,Reporting,Reward,State,Subscription,Template,UserActivity
admin.site.register(ImportedFile)
admin.site.register(ConsumerOffer)
admin.site.register(LoanAccount)
admin.site.register(Payment)
admin.site.register(BusinessOwnerData)
admin.site.register(MembershipPlan)
admin.site.register(State)
admin.site.register(BillingDetails)
admin.site.register(Country)
admin.site.register(Subscription)
admin.site.register(CreditorBusinessData)
admin.site.register(City)
admin.site.register(Donation)
admin.site.register(Reward)
admin.site.register(MerchantAccount)
admin.site.register(Content)
admin.site.register(BusinessRule)
admin.site.register(Reporting)
admin.site.register(Template)
admin.site.register(UserActivity)
admin.site.register(Campaign)
admin.site.register(Address)

# Register your models here.
